server:
  context-path: /seller
  port: 8082
rpc:
  client:
    url: http://localhost:8080/manager/
    basePackage: io.sanye.open.financial.api
logging:
  level:
    com.googlecode.jsonrpc4j: debug
#    basePackage: io.sanye.open.financial.api






